spring:
  profiles:
    default: local
    group:
      local:
        mysql-local
      prod:
        mysql-prod

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
secret-key-source: ${SECRET_KEY_SOURCE}
