spring:
  config:
    activate:
      on-profile: prod
    import:
      -classpath: mysql.yml

  jpa:
    generate-ddl: 'false'
    database: mysql
    defer-datasource-initialization: true
    open-in-view: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true



