spring:
  config:
    activate:
      on-profile: local

  jpa:
    generate-ddl: 'true'
    database: mysql
    defer-datasource-initialization: true
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true



