spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    generate-ddl: 'false'
    database: mysql
    defer-datasource-initialization: true
    open-in-view: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        show_sql: true

  datasource:
    url: ENC(idBkAGGqOOYYy+OWUGrVjxzmGchF1ZclLcgDxKxfofcEplUTkqwESuRIBkjyeLlz)
    password: ENC(kqXSpAR86DLQY1/cFKO+Oji/K2rQ98Mn)
    username: ENC(H6no8sV3qu/TEHspw8d/nQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: ${DB_NAME}

#jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
secret-key-source: ${SECRET_KEY_SOURCE}

